### ISSUE TITLE
Uncaught Type Error from Atom right-click menu

### ISSUE THREAD

**Issue by ghost** [m-hall/eslint-fixer#8] opened 2017-01-04 19:47 UTC
Right-clicking and running eslint --fix throws an error

1. Install eslint-fixer
2. Right-click on a file and choose run eslint --fix

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**Cygwin Version**: 2.6.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [eslint-fixer](https://github.com/m-hall/eslint-fixer) package, v1.2.1

 ### Stack Trace
 Uncaught TypeError: Path must be a string. Received [ 'path\\to\\file.js' ]
``` 
At path.js:7 TypeError: Path must be a string. Received [ 'path\\to\\file.js' ]
    at assertPath (path.js:7:11)
    at Object.relative (path.js:537:5) 
    at C:\Users\Programming\.atom\packages\eslint-fixer\lib\atom-eslint-fix.js:40:28
    at Array.forEach (native)
    at Object.getCurrentWorkingDir (C:\Users\Programming\.atom\packages\eslint-fixer\lib\atom-eslint-fix.js:38:37)
    at Object.exec (C:\Users\Programming\.atom\packages\eslint-fixer\lib\atom-eslint-fix.js:82:24)
    at Object.runTreeView (C:\Users\Programming\.atom\packages\eslint-fixer\lib\atom-eslint-fix.js:65:14)
    at HTMLSpanElement.atom-eslint-fix:run-tree-view (C:\Users\Programming\.atom\packages\eslint-fixer\lib\atom-eslint-fix.js:28:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Programming\AppData\Local\atom\app-1.12.8\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Programming\AppData\Local\atom\app-1.12.8\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Programming\AppData\Local\atom\app-1.12.8\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Programming\AppData\Local\atom\app-1.12.8\resources\app.asar\src\atom-environment.js:1142:28)
    at EventEmitter.outerCallback (C:\Users\Programming\AppData\Local\atom\app-1.12.8\resources\app.asar\src\application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by Matus-Stastny** [comment] 2017-01-13 15:29
I have an identical issue on MAC (10.11.6) using Atom 1.13.0

**Comment by m-hall** [comment] 2017-04-23 00:55
This is a duplicate of #12.

**Closed as completed by m-hall** 2017-04-23 00:55 UTC
